name: Build and deploy Docker app to Azure

on: [push]

env:
  username_repo: devnxt1/holmes
  PROJECTID: ${{secrets.PROJ_ID}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} #save corresponding secrets in repo PROJ_ID
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - run: |
        docker build . -t ${{ env.username_repo }}:${{ github.sha }}
        docker push ${{ env.username_repo }}:${{ github.sha }} 
        docker tag ${{ env.username_repo }}:${{ github.sha }} gcr.io/${{env.PROJECTID}}/devnext-app:${{ github.run_number }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{env.PROJECTID}}
        service_account_key: ${{ secrets.GCPKEY3 }}

    - run: |
      
        docker push gcr.io/${{env.PROJECTID}}/devnext-app:${{ github.run_number }}
        gcloud run deploy automation1 --region us-central1 --image gcr.io/${{env.PROJECTID}}/devnext-app:${{ github.run_number }}
